version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: dbp_mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      TZ: Asia/Seoul  # 시간대 설정
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development
      - TZ=Asia/Seoul  # 시간대 설정
